### ISSUE TITLE
The translated text does not fit into the layout

### ISSUE THREAD

**Issue by rkttu** [LiaScript/lia-localization#3]
Thanks for giving me a contribution opportunity. It was a pleasant experience. :-)

I confirmed the localization text applied well. But in my desktop environment, the translated text does not fit into the layout. 

![image](https://user-images.githubusercontent.com/1297346/131122260-c451292e-c7df-42a5-a666-3dc586a39b1c.png)

![image](https://user-images.githubusercontent.com/1297346/131122514-cb749639-6fa9-4b38-9234-2f5a68a6e551.png)

Also, some text does not translated.

![image](https://user-images.githubusercontent.com/1297346/131122556-e0347ec7-c5ce-49b7-b717-97c4151baad3.png)

Environment
- Microsoft Edge 92.0.902.78 (Official, x64)
- Windows 10 21H1 (10.0.19043.1165, x64)

**Comment by rkttu** [comment]
@andre-dietrich Great! And the Chinese and Japanese issues that we usually deal with together with Korean. It's efficient to say CJK in groups and deal with it all at once.

In Korean (I cannot confirm Japanese or Chinese), the Windows font panel shows as '가나다AaBbYyZz' (pronounced as 'ga-na-da') as shown in the figure below. The Korean letter corresponding to the English letter 'A' is '가.' Maybe In Japanese, ABC sounds like 'いろは' (pronounced 'iroha').

![image](https://user-images.githubusercontent.com/1297346/131243685-5834e711-72fc-44ab-9a48-8d9c9b821604.png)

**Comment by andre-dietrich** [comment]
@rkttu Thank you very much for your help. I just updated the translations and added also missing ones, which were previously part as plain text within the source code. I added the English parts that are missing to your Korean translation. If you have some time, then I will update these as soon as possible. The styling issues should then also been resolved within the next version.

I also added a base.abc entry to the Englisch translation. After some research on icons, it seemed to me, that mostly "Aa" is used as an indicator for font and size. So you can also add your solutions to it.

Concerning the light and dark mode, these texts have also been defined within the source-code, so we will make use of the translations. I changed the "c.dark|bright" to "Dark-Mode" and "Light-Mode", if you could also add this "mode" appendix to your translation, this would be great.

A translation for editor was also added, but I would leave the translations for the specific styles out at the moment. The reason is, that the naming does not often make sense and these styles are bound to the ace editor, that we are using at the moment. We wanted to switch to Microsoft's monaca, because it provides better accessibility features, but it does not really work well on mobile. Code-Mirrors accessible version 6 is not ready yet, so we stuck with ace. To be more clear in this case, I added "editor-style"... 

Greetings ...

**Comment by andre-dietrich** [comment]
@rkttu ... Hi, just added some missing Korean translations (using Google :see_no_evil: ). It would be kind if you could check this, so I would push another version today also with the fixed CSS bug ...

Regards ...

**Comment by rkttu** [comment]
I'm on a long vacation right now. I think I will be able to check again at the end of this month or early next month. I will reply back as soon as I confirm. 🙏

**Comment by rkttu** [comment]
I've confirmed that the layout issue has been fixed. It would be good to close this issue. Separately, I think it is necessary to refine the translated text more naturally, so I will send an additional pull request. 👍 

![image](https://user-images.githubusercontent.com/1297346/135190602-506641ab-96e4-4abb-8a9f-07ced327c0aa.png)

![image](https://user-images.githubusercontent.com/1297346/135190626-ea35d6c5-291f-46c3-aa47-8e6213218efc.png)

![image](https://user-images.githubusercontent.com/1297346/135190641-fff9ddc5-5d9f-40be-b04e-8d5439d75b80.png)

![image](https://user-images.githubusercontent.com/1297346/135190652-08bf9017-e22a-4ae0-9507-30af8709b391.png)

![image](https://user-images.githubusercontent.com/1297346/135190677-c088c42e-8359-4eab-97c0-86d79f9ca39b.png)

**Comment by andre-dietrich** [comment]
Thanks, a corrected translation would be great ... ;-)
